---
html_document: default
---

```{r}
knitr::opts_chunk$set(echo = FALSE)
```

```{r, message=FALSE}
library(edgeR)
library(EnhancedVolcano)
library(pheatmap)
library(RColorBrewer)
```

pet2
```{r, fig.height = 10, fig.width = 10}
pet2_counts <- read.table('/Users/spencerseale/Desktop/UO/bi425_525/de_analysis/pet2_counts.tsv', row.names=1)
pet2_counts <- pet2_counts[1:(nrow(pet2_counts)-5),]

pet2_group <- c("102219_WT_pet2-2_1", "102219_WT_pet2-2_2", "102219_pet2-2_4", "102219_pet2-2_5", "102219_pet2-2_7")

pet2_conditions <- c("pet2_wt", "pet2_wt", "pet2_mt", "pet2_mt", "pet2_mt")

#setting dif gene expression list and normalizing
pet2_dge.er <- DGEList(counts=pet2_counts)
pet2_dge.er <- calcNormFactors(pet2_dge.er)
#pet2_dge.er
#setting design variable
pet2_design.er <- model.matrix(~0 + pet2_conditions)

#pet2_design.er

#running all dispersion options
pet2_dge.er <- estimateGLMCommonDisp(pet2_dge.er, pet2_design.er)
pet2_dge.er <- estimateGLMTrendedDisp(pet2_dge.er, pet2_design.er)
pet2_dge.er <- estimateGLMTagwiseDisp(pet2_dge.er, pet2_design.er)

#fitting a negative binomial generalized log-linear model
pet2_fit.er <- glmFit(pet2_dge.er, pet2_design.er)

#setting all contrasts
contrasts <- makeContrasts(pet2wt_vs_pet2mt=pet2_conditionspet2_wt-pet2_conditionspet2_mt, levels=pet2_design.er)

pet2_lrt <- glmLRT(pet2_fit.er, contrast=contrasts[,"pet2wt_vs_pet2mt"])

#log2 of 2 = 1
#pet2_de <- decideTestsDGE(pet2_lrt, p.value = 0.00001, lfc=1)

pet2_logCPM <- cpm(pet2_dge.er, prior.count=2, log=TRUE)

pet2_order <- order(pet2_lrt$table$PValue)

pet2_logCPM <- pet2_logCPM[pet2_order[1:500],]

coolmap(pet2_logCPM, labRow="", labCol=pet2_group, margins = c(8,8), cexRow=0.75, cexCol=1, srtCol=45, cluster.by="expression level", col="redgreen")

#pval = .00001
EnhancedVolcano(pet2_lrt$table, x = "logFC", y = "PValue", lab=rownames(pet2_lrt$table), title="pet2 wt vs mt", subtitle="+ wt", FCcutoff=1)

#getting table of values 
#output significant genes from volcano plot to txt
FC_sub_pet2 <- subset(pet2_lrt$table, abs(logFC) >= 1)
P_FC_sub_pet2 <- subset(FC_sub_pet2, PValue <= 0.00001)
write.table(P_FC_sub_pet2,"pet2_sig_lf2c.txt",sep="\t",row.names=TRUE)
```



ptac12
```{r, fig.height = 10, fig.width = 10}
ptac12_counts <- read.table('/Users/spencerseale/Desktop/UO/bi425_525/de_analysis/ptac12_counts.tsv', row.names=1)
ptac12_counts <- ptac12_counts[1:(nrow(ptac12_counts)-5),]
ptac12_counts <- ptac12_counts[,c(1,2,4,5)]

#ptac12_group <- c("102219_WT_ptac12-2_17", "102219_WT_ptac12-2_29", "102219_ptac12-2_19", "102219_ptac12-2_20", "102219_ptac12-2_21")
ptac12_group <- c("102219_WT_ptac12-2_17", "102219_WT_ptac12-2_29", "102219_ptac12-2_20", "102219_ptac12-2_21")

#ptac12_conditions <- c("ptac12_wt", "ptac12_wt", "ptac12_mt", "ptac12_mt", "ptac12_mt")
ptac12_conditions <- c("ptac12_wt", "ptac12_wt", "ptac12_mt", "ptac12_mt")

#setting dif gene expression list and normalizing
ptac12_dge.er <- DGEList(counts=ptac12_counts)
ptac12_dge.er <- calcNormFactors(ptac12_dge.er)

#setting design variable
ptac12_design.er <- model.matrix(~0 + ptac12_conditions)

#running all dispersion options
ptac12_dge.er <- estimateGLMCommonDisp(ptac12_dge.er, ptac12_design.er)
ptac12_dge.er <- estimateGLMTrendedDisp(ptac12_dge.er, ptac12_design.er)
ptac12_dge.er <- estimateGLMTagwiseDisp(ptac12_dge.er, ptac12_design.er)

#fitting a negative binomial generalized log-linear model
ptac12_fit.er <- glmFit(ptac12_dge.er, ptac12_design.er)

#setting all contrasts
contrasts <- makeContrasts(ptac12wt_vs_ptac12mt=ptac12_conditionsptac12_wt-ptac12_conditionsptac12_mt, levels=ptac12_design.er)

ptac12_lrt <- glmLRT(ptac12_fit.er, contrast=contrasts[,"ptac12wt_vs_ptac12mt"])

#log2 of 2 = 1
#ptac12_de <- decideTestsDGE(ptac12_lrt, p.value = 0.00001, lfc=1)

ptac12_logCPM <- cpm(ptac12_dge.er, prior.count=2, log=TRUE)

ptac12_order <- order(ptac12_lrt$table$PValue)

ptac12_logCPM <- ptac12_logCPM[ptac12_order[1:500],]

coolmap(ptac12_logCPM, labRow="", labCol=ptac12_group, margins = c(8,8), cexRow=0.75, cexCol=1, srtCol=45, cluster.by="expression level", col="redgreen")

#pval = .00001
#logf2change cutoff 4
EnhancedVolcano(ptac12_lrt$table, x = "logFC", y = "PValue", lab=rownames(ptac12_lrt$table), title="ptac12 wt vs mt", subtitle="+ wt", FCcutoff=1)

#getting table of values 
#output significant genes from volcano plot to txt 
FC_sub_ptac12 <- subset(ptac12_lrt$table, abs(logFC) >= 1)
P_FC_sub_ptac12 <- subset(FC_sub_ptac12, PValue <= 0.00001)
write.table(P_FC_sub_ptac12,"ptac12_sig_lf2c.txt",sep="\t",row.names=TRUE)



write.table(ptac12_lrt$table,"saskia-kait_ptac12wt_vs_mut_sig_lf2c.txt",sep="\t",row.names=TRUE)
```




ptac2
```{r, fig.height = 10, fig.width = 10}
ptac2_counts <- read.table('/Users/spencerseale/Desktop/UO/bi425_525/de_analysis/ptac2_counts.tsv', row.names=1)
ptac2_counts <- ptac2_counts[1:(nrow(ptac2_counts)-5),]
ptac2_counts <- ptac2_counts[,c(1,2,4,5)]

#ptac2_group <- c("102219_WT_ptac2-3_8", "102219_WT_ptac2-3_9", "102219_ptac2-3_12", "102219_ptac2-3_14", "102219_ptac2-3_30")
ptac2_group <- c("102219_WT_ptac2-3_8", "102219_WT_ptac2-3_9", "102219_ptac2-3_14", "102219_ptac2-3_30")

#ptac2_conditions <- c("ptac2_wt", "ptac2_wt", "ptac2_mt", "ptac2_mt", "ptac2_mt")
ptac2_conditions <- c("ptac2_wt", "ptac2_wt", "ptac2_mt", "ptac2_mt")

#setting dif gene expression list and normalizing
ptac2_dge.er <- DGEList(counts=ptac2_counts)
ptac2_dge.er <- calcNormFactors(ptac2_dge.er)

#setting design variable
ptac2_design.er <- model.matrix(~0 + ptac2_conditions)

#running all dispersion options
ptac2_dge.er <- estimateGLMCommonDisp(ptac2_dge.er, ptac2_design.er)
ptac2_dge.er <- estimateGLMTrendedDisp(ptac2_dge.er, ptac2_design.er)
ptac2_dge.er <- estimateGLMTagwiseDisp(ptac2_dge.er, ptac2_design.er)

#fitting a negative binomial generalized log-linear model
ptac2_fit.er <- glmFit(ptac2_dge.er, ptac2_design.er)

#setting all contrasts
contrasts <- makeContrasts(ptac2wt_vs_ptac2mt=ptac2_conditionsptac2_wt-ptac2_conditionsptac2_mt, levels=ptac2_design.er)

ptac2_lrt <- glmLRT(ptac2_fit.er, contrast=contrasts[,"ptac2wt_vs_ptac2mt"])

#log2 of 2 = 1
#ptac2_de <- decideTestsDGE(ptac2_lrt, p.value = 0.00001, lfc=1)

ptac2_logCPM <- cpm(ptac2_dge.er, prior.count=2, log=TRUE)

ptac2_order <- order(ptac2_lrt$table$PValue)

ptac2_logCPM <- ptac2_logCPM[ptac2_order[1:500],]

coolmap(ptac2_logCPM, labRow="", labCol=ptac2_group, margins = c(8,8), cexRow=0.75, cexCol=1, srtCol=45, cluster.by="expression level", col="redgreen")

#pval = .00001
EnhancedVolcano(ptac2_lrt$table, x = "logFC", y = "PValue", lab=rownames(ptac2_lrt$table), title="ptac2 wt vs mt", subtitle="+ wt", FCcutoff=1)

#getting table of values 
#output significant genes from volcano plot to txt
FC_sub_ptac2 <- subset(ptac2_lrt$table, abs(logFC) >= 1)
P_FC_sub_ptac2 <- subset(FC_sub_ptac2, PValue <= 0.05)
write.table(P_FC_sub_ptac2,"ptac2_sig_lf2c.txt",sep="\t",row.names=TRUE)

#write.table(ptac2_lrt$table,"saskia-kait_ptac2_sig_lf2c.txt",sep="\t",row.names=TRUE)
```

ptac12 vs ptac2
```{r}
ptac12_mut <- ptac12_counts[,c(3,4)]
colnames(ptac12_mut) <- c("102219_ptac12-2_20", "102219_ptac12-2_21")
ptac2_mut <- ptac2_counts[,c(3,4)]
colnames(ptac2_mut) <- c("102219_ptac2-3_14", "102219_ptac2-3_30")

ptac12_2_mut <- merge(ptac12_mut, ptac2_mut, by="row.names")
row.names(ptac12_2_mut) <- ptac12_2_mut$Row.names
ptac12_2_mut <- ptac12_2_mut[,2:5]
#ptac12_2_mut


ptac12_2_conditions <- c("ptac12_mt", "ptac12_mt", "ptac2_mt", "ptac2_mt")

#setting dif gene expression list and normalizing
ptac12_2_dge.er <- DGEList(counts=ptac12_2_mut)
ptac12_2_dge.er <- calcNormFactors(ptac12_2_dge.er)

#setting design variable
ptac12_2_design.er <- model.matrix(~0 + ptac12_2_conditions)

#running all dispersion options
ptac12_2_dge.er <- estimateGLMCommonDisp(ptac12_2_dge.er, ptac12_2_design.er)
ptac12_2_dge.er <- estimateGLMTrendedDisp(ptac12_2_dge.er, ptac12_2_design.er)
ptac12_2_dge.er <- estimateGLMTagwiseDisp(ptac12_2_dge.er, ptac12_2_design.er)

#fitting a negative binomial generalized log-linear model
ptac12_2_fit.er <- glmFit(ptac12_2_dge.er, ptac12_2_design.er)

#setting all contrasts
contrasts <- makeContrasts(ptac12mt_vs_ptac2mt=ptac12_2_conditionsptac12_mt-ptac12_2_conditionsptac2_mt, levels=ptac12_2_design.er)

ptac12_2_lrt <- glmLRT(ptac12_fit.er, contrast=contrasts[,"ptac12mt_vs_ptac2mt"])

#output significant genes from volcano plot to txt
FC_sub_ptac12_2 <- subset(ptac12_2_lrt$table, abs(logFC) >= 1)
P_FC_sub_ptac12_2 <- subset(FC_sub_ptac12_2, PValue <= 0.00001)
write.table(P_FC_sub_ptac12_2,"ptac12-ptac2_sig_lf2c.txt",sep="\t",row.names=TRUE)
```

### ptac12 vs pet2
```{r}
ptac12_mut <- ptac12_counts[,c(3,4)]
colnames(ptac12_mut) <- c("102219_ptac12-2_20", "102219_ptac12-2_21")

pet2_mut <- pet2_counts[,c(3-5)]
colnames(pet2_mut) <- c("102219_pet2-2_4", "102219_pet2-2_5", "102219_pet2-2_7")

pet2_ptac12_mut <- merge(ptac12_mut, pet2_mut, by="row.names")
row.names(pet2_ptac12_mut) <- pet2_ptac12_mut$Row.names
pet2_ptac12_mut <- pet2_ptac12_mut[,2:6]

pet2_ptac12_conditions <- c("ptac12_mt", "ptac12_mt", "pet2_mt", "pet2_mt", "pet2_mt")

#setting dif gene expression list and normalizing
pet2_ptac12_dge.er <- DGEList(counts=pet2_ptac12_mut)
pet2_ptac12_dge.er <- calcNormFactors(pet2_ptac12_dge.er)

#setting design variable
pet2_ptac12_design.er <- model.matrix(~0 + pet2_ptac12_conditions)

#running all dispersion options
pet2_ptac12_dge.er <- estimateGLMCommonDisp(pet2_ptac12_dge.er, pet2_ptac12_design.er)
pet2_ptac12_dge.er <- estimateGLMTrendedDisp(pet2_ptac12_dge.er, pet2_ptac12_design.er)
pet2_ptac12_dge.er <- estimateGLMTagwiseDisp(pet2_ptac12_dge.er, pet2_ptac12_design.er)

#fitting a negative binomial generalized log-linear model
pet2_ptac12_fit.er <- glmFit(pet2_ptac12_dge.er, pet2_ptac12_design.er)

#setting all contrasts
contrasts <- makeContrasts(ptac12mt_vs_pet2mt=pet2_ptac12_conditionsptac12_mt-pet2_ptac12_conditionspet2_mt, levels=pet2_ptac12_design.er)

pet2_ptac12_lrt <- glmLRT(pet2_ptac12_fit.er, contrast=contrasts[,"ptac12mt_vs_pet2mt"])

pdf("ptac12mt_vs_pet2mt.pdf")
EnhancedVolcano(pet2_ptac12_lrt$table, x = "logFC", y = "PValue", lab=rownames(pet2_ptac12_lrt$table), title="ptac12 mt vs pet2 mt", subtitle="+ ptac12", FCcutoff=1)
dev.off()

#output significant genes from volcano plot to txt
FC_sub_pet2_ptac12 <- subset(pet2_ptac12_lrt$table, abs(logFC) >= 1)
P_FC_sub_pet2_ptac12 <- subset(FC_sub_pet2_ptac12, PValue <= 0.00001)
write.table(P_FC_sub_pet2_ptac12,"ptac12-pet2_sig_lf2c.txt",sep="\t",row.names=TRUE)

```

```{r, fig.height = 10, fig.width = 10, message=FALSE, warning=FALSE}
#constructing heat map of log2fold changes
pet2_lfc <- pet2_lrt$table[,c(1,4)]
pet2_lfc <- pet2_lfc[order(pet2_lfc$PValue),]
#pet2_lfc$logFC = 2^pet2_lfc$logFC
colnames(pet2_lfc)[1] <- "pet2_wt_mt"


ptac12_lfc <- ptac12_lrt$table[,c(1,4)]
ptac12_lfc <- ptac12_lfc[order(ptac12_lfc$PValue),]
#ptac12_lfc$logFC = 2^ptac12_lfc$logFC
colnames(ptac12_lfc)[1] <- "ptac12_wt_mt"


ptac2_lfc <- ptac2_lrt$table[,c(1,4)]
ptac2_lfc <- ptac2_lfc[order(ptac2_lfc$PValue),]
#ptac2_lfc$logFC = 2^ptac2_lfc$logFC
colnames(ptac2_lfc)[1] <- "ptac2_wt_mt"


ptac12_2_lfc <- ptac12_2_lrt$table[,c(1,4)]
ptac12_2_lfc <- ptac12_2_lfc[order(ptac12_2_lfc$PValue),]
colnames(ptac12_2_lfc)[1] <- "ptac12mt_ptac2mt"



merged_lfc <- merge(pet2_lfc, ptac12_lfc, by="row.names")
row.names(merged_lfc) <- merged_lfc$Row.names
merged_lfc <- merge(merged_lfc, ptac2_lfc, by="row.names")
row.names(merged_lfc) <- merged_lfc$Row.names
merged_lfc <- merge(merged_lfc, ptac12_2_lfc, by="row.names")
row.names(merged_lfc) <- merged_lfc$Row.names

merged_lfc <- merged_lfc[,4:ncol(merged_lfc)]
merged_lfc_only <- merged_lfc[,c(1,3,5,7)]

#logfc set to 4
merged_lfc_sig <- subset(merged_lfc_only, pet2_wt_mt >= abs(4) | ptac12_wt_mt >= abs(4) | ptac2_wt_mt >= abs(4) | ptac12mt_ptac2mt >= abs(4))

pheatmap(merged_lfc_sig, show_rownames = FALSE, fontsize = 18, clustering_method = "ward.D2", main = "Zea Mays Log2fold", treeheight_col = 0, angle_col = 45, color = colorRampPalette(rev(brewer.pal(n = 9, name = "YlGnBu")))(100))
```






